apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodo-deployment
  labels:
    app: microtodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microtodo
  template:
    metadata:
      labels:
        app: microtodo
    spec:
      containers:
      - name: microtodo-container
        image: ruchi1010/myapp:latest   # Aapka image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
